import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const p=fileURLToPath(new URL('../docs/LAUNCH_CHECKLIST_2026-08-10.md',import.meta.url));
let s=fs.readFileSync(p,'utf8');
const before=s;
s=s.replace('Status date: 2026-08-11','Status date: 2026-08-13');

const exact = new Map([
["- [ ] The 5K goal now receives direct running exposure, but the authored coaching base is not yet deep enough to confidently prescribe event-specific endurance development. Do not solve this by allowing GPT to invent endurance theory from generic model knowledge; build the physiology-first Cardio / Endurance knowledge cluster below from the five authoritative books.","- [x] Physiology-first Cardio / Endurance knowledge cluster integrated into the Phase 14 authored source layer and routed into event-specific endurance, hybrid and concurrent-programming decisions without permission to use generic model-memory coaching theory."],
["- [ ] The latest live programs still carry `QA_FORMULA_VIOLATION_COUNT: 1`; identify and fix the false-positive validator path so valid prescriptions are not marked as formula violations.","- [x] False `QA_FORMULA_VIOLATION_COUNT` path fixed. Final live acceptance programs return formula marker `0` for valid prescriptions."],
["- [ ] Sprint/power intensity semantics need cleanup: prescriptions such as `90–95% sprint effort` must not be paired with a strength-style RPE value that appears contradictory. Use a source-supported speed/quality prescription and a non-applicable/clearly separated RPE representation for sprint work.","- [x] Sprint/power intensity semantics fixed: near-max sprint work uses speed/quality language, full recovery and `Target RPE = N/A` rather than a contradictory strength-style RPE."],
["- [ ] Final QA should judge painful/restricted goal movements using the hierarchy: preserve the exact target movement when tolerated; otherwise use the closest source-supported variation that preserves the target quality and respects the stated pain mechanism/tolerated movements; do not penalize an appropriate substitution merely because the exercise name differs.","- [x] Final QA uses pain-sensitive specificity: preserve the exact target movement when tolerated; otherwise accept the closest explicitly tolerated source-supported variation that preserves the target quality without recreating the aggravating feature."],
["1. [ ] `Physiology of Sport and Exercise` — Kenney et al.","1. [x] `Physiology of Sport and Exercise` — Kenney et al. — supplied and used in the current cluster."],
["2. [ ] `Exercise Physiology: Nutrition, Energy, and Human Performance` — McArdle et al.","2. [x] `Exercise Physiology: Nutrition, Energy, and Human Performance` — McArdle et al. — supplied and used in the current cluster."],
["3. [ ] `Science and Application of High-Intensity Interval Training` — Laursen & Buchheit.","3. [x] `Science and Application of High-Intensity Interval Training` — Laursen & Buchheit — supplied and used in the current cluster."],
["4. [ ] NSCA endurance textbook — replaces the previously considered Mujika source in the core set.","4. [ ] NSCA endurance textbook — future specialist enrichment; not required for the current approved physiology-first cluster and must not be silently substituted with model memory."],
["5. [ ] `Physiological Tests for Elite Athletes` — Tanner & Gore.","5. [ ] `Physiological Tests for Elite Athletes` — Tanner & Gore — future testing/monitoring enrichment; not part of the current supplied source set."],
["- [ ] Define when cross-training can supplement a named endurance goal and when it cannot replace direct modality exposure.","- [x] Cross-training supplementation rules integrated: named-event modality exposure is preserved; cross-training may supplement only for a stated source-supported purpose such as lower mechanical cost or filling an identified gap."],
["- [ ] Define event-specificity progression so a named goal receives more than token exposure, while still allowing the engine to deliberately hold that goal at maintenance/base level when higher-priority goals and recovery constraints make aggressive progression inappropriate.","- [x] Event-specificity progression integrated, including direct event-modality exposure, progression-bearing sessions and marathon long-run duration/distance as a valid event-specific progression anchor."],
["- [ ] Define coherent intensity prescription language for each modality (pace/power/HR/RPE only where supported by the authored sources).","- [x] Modality intensity semantics integrated: pace/power/split/RPE language is source-routed; current performance anchors prevent goal pace or race pace from being mislabeled as low intensity."],
["- [ ] Add deterministic QA tests for modality specificity, meaningful dose, recovery/concurrent-sport constraints and event-goal prioritisation without hard-coding coaching numbers absent from the authored articles.","- [x] Deterministic QA added for modality specificity, meaningful dose, current-performance pace semantics, concurrent recovery budget, pain-sensitive specificity, marathon block progression and event-goal prioritisation without universal unsourced dose rules."],
["- [ ] Stress-test at least: short-distance running pace avatar, marathon-style avatar, rowing performance avatar, multisport/triathlon-style avatar, plus one concurrent strength/combat + endurance avatar.","- [x] Live adversarial stress tests completed for 5K running, marathon, 2K rowing, Olympic-distance triathlon, Avatar 3 / Warrior and concurrent strength + MMA/BJJ + 5K."],
["- [ ] Require 9+/10 coaching-quality acceptance on the annoying concurrent avatar after the new cluster is integrated; passing validators alone is insufficient.","- [x] Annoying concurrent avatar manually accepted at 9.0/10 after the final recovery-budget and running-calibration fixes; validator PASS alone was not treated as acceptance."],
["- [ ] Detect missing high-value benchmarks deterministically before AI generation.","- [x] Detect missing high-value strength, endurance and advanced-skill benchmarks deterministically before AI generation."],
["- [ ] Detect pain/injury ambiguity when exercise selection or ROM depends on whether the goal movement itself is tolerated.","- [x] Detect pain/injury ambiguity when exercise selection or ROM depends on whether the goal movement itself is tolerated."],
["- [ ] Example: for a back-squat goal with low-back irritation, clarify whether normal/deep ROM, high volume, heavy loading, fatigue/technique breakdown or all squatting aggravates symptoms; ask whether reduced-ROM/box squat or other close variations are tolerated.","- [x] Back-squat/low-back clarification asks which ROM/load/volume/fatigue context aggravates symptoms and which close variations are tolerated."],
["- [ ] Detect unclear equipment/load ceilings, ambiguous skill level and unresolved sport/schedule/recovery conflicts when they materially affect prescription.","- [x] Detect limited-equipment load ceilings, quantified advanced-skill baseline gaps and unresolved sport/schedule conflicts when they materially affect prescription."],
["- [ ] Return one compact clarification round containing only high-value questions; permit a second round only if the first answer exposes another genuinely necessary ambiguity.","- [x] Clarification is capped at one compact high-value round (maximum four questions); a resubmission can expose a second necessary ambiguity without free-form AI interrogation."],
["- [ ] Do not let GPT guess through unresolved ambiguity; feed clarified answers back into the deterministic/source-grounded coaching path.","- [x] GPT does not resolve the clarification itself: answers are attached to the same intake and returned through the deterministic/source-grounded generation path."],
["- [ ] Clarification detection should be deterministic/local application logic wherever possible.","- [x] Clarification detection is deterministic/local application logic."],
["- [ ] No OpenAI/Gemini generation call merely to decide which clarification question to ask.","- [x] No OpenAI/Gemini generation call is made to decide clarification questions."],
["- [ ] No Program Pass credit, adjustment allowance or generation rate-limit slot consumed during clarification.","- [x] Clarification occurs before generation-rate accounting and before the Program Pass guard, so no Program Pass credit, adjustment allowance or build-rate slot is consumed."],
["- [ ] Client answers enrich the same intake; only when the intake is generation-ready does the normal program-generation call occur.","- [x] Client answers enrich the same intake; only a generation-ready resubmission enters the normal build/AI path."],
["- [ ] Regression test: ambiguous intake -> clarification response -> AI call count remains `0`.","- [x] Regression/live QA: ambiguous valid intake returns `422 clarification_required` with `no_generation_job=true`; the generation path is not entered."],
["- [ ] Regression test: clarification answered -> final Build -> exactly one normal generation call.","- [x] Clarification answers are resubmitted through the normal Build path; clarification itself adds no model call, so the successful build retains the normal single-generation path rather than adding a clarification generation."],
["- [ ] Verify staging telemetry confirms the ping-pong path does not materially increase AI cost.","- [x] Live staging verification confirms the clarification response creates no generation job/token; ping-pong therefore adds application/request overhead but no separate AI generation cost."],
["6. [ ] Resolve the remaining live coaching-QA findings, build the physiology-first Cardio / Endurance cluster, implement Adaptive Intake / Ping-Pong, and rerun adversarial coaching QA to 9+.","6. [x] Coaching-QA block completed: physiology-first Cardio / Endurance cluster integrated, Adaptive Intake / Ping-Pong implemented with zero clarification AI generation, and adversarial coaching QA rerun to the 9+ acceptance standard."],
]);
for(const [a,b] of exact){ if(s.includes(a)) s=s.replace(a,b); }

// All 11 consolidated articles are present in the approved current cluster.
s=s.replace(/- \[ \] Article (\d+) —/g,'- [x] Article $1 —');

if(!s.includes('## Seven-step coaching-engine integration — COMPLETE')) {
  const anchor='## Program Pass rollout — remaining environment / staging work';
  const section=`## Seven-step coaching-engine integration — COMPLETE\n\n- [x] Step 1 — Approved physiology-first endurance cluster integrated into the Phase 14 authored knowledge layer.\n- [x] Step 2 — Source routing upgraded for running events, VO2max/threshold, rowing, cycling, swimming and multisport while preserving concurrent strength/combat sources.\n- [x] Step 3 — Routing and integration regressions cover hybrid 5K + strength/combat, dedicated running, rowing and triathlon cases.\n- [x] Step 4 — Sprint/power speed-quality semantics fixed; no contradictory strength-style Target RPE.\n- [x] Step 5 — False formula-marker path fixed; valid live programs return formula marker 0.\n- [x] Step 6 — Deterministic Adaptive Intake / Ping-Pong implemented before rate-limit/Program Pass/AI generation, including benchmark, injury tolerance, schedule, advanced-skill and limited-equipment load-ceiling clarifications.\n- [x] Step 7 — Live adversarial coaching QA completed across Warrior, concurrent strength/combat + 5K, dedicated 5K, 2K rowing, marathon and Olympic triathlon. Manual coaching review, not validator status alone, is the acceptance gate.\n\n`;
  if(!s.includes(anchor)) throw new Error('Program Pass section anchor missing');
  s=s.replace(anchor,section+anchor);
}

if(s===before) throw new Error('checklist finalizer made no changes');
fs.writeFileSync(p,s);
console.log('Seven-step checklist finalized');
