import fs from "node:fs";
const BASE=process.env.LIVE_BASE||"https://raz-coaching-platform.onrender.com";
const outDir="stress-output";fs.mkdirSync(outDir,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function jf(path,init={}){const r=await fetch(BASE+path,{...init,headers:{"Content-Type":"application/json",...(init.headers||{})}});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={raw:t}};if(!r.ok)throw new Error(`${path} HTTP ${r.status}: ${t.slice(0,500)}`);return d;}
async function waitDeploy(){const end=Date.now()+10*60*1000;let last;while(Date.now()<end){last=await jf("/api/health").catch(()=>null);if(last?.ok&&last?.mode==="openai"&&last?.openai_execution_path==="deterministic-skeleton-v5.2.10-source-grounded")return last;await sleep(5000);}throw new Error(`deployment gate timeout ${JSON.stringify(last)}`);}
const intake={
  primary_goals:["Parallel box squat: build toward 180 kg x10 or above 210 kg maximal strength","One-Arm Pull-up: progress toward 4 strict reps","Strict Overhead Press: progress toward approximately 100 kg while preserving shoulder quality"],
  secondary_goals:["Improve aerobic base with 2-3 low-fatigue Zone 2 exposures","Preserve BJJ/MMA mat performance and recovery","Maintain useful hypertrophy without junk volume"],
  experience:"advanced",days_per_week:"4",available_gym_days:["Mon","Wed","Thu","Sat"],session_length:"60-70",bodyweight:"85 kg",height:"173 cm",
  equipment:"Commercial gym with squat rack, barbells, plates, pull-up bars, dip belt, cable stacks, dumbbells, benches and cardio machines.",training_location:"commercial_gym",language:"en",split_preference:"coach_decide",
  current_numbers:"Weighted chin-up approximately +80 kg external-load 1RM. One-arm pull-up current ability approximately 2 strict reps / advanced direct OAP work. Historical strict overhead press 80 kg x4. Push press 80 kg x3 at about RPE 9-9.5 while fatigued. Speed parallel box squat 100-105 kg is well tolerated. Historical back squat 205 kg at about 81-82 kg bodyweight. Historical Romanian deadlift 240 kg x4 around RIR 1, but heavy hinge/deep squat loading is not currently the preferred spinal stressor.",
  injuries:"L3-L4 sensitive low back with intermittent sciatica, aggravated mainly by prolonged walking/very soft bed and potentially deep heavy loaded squatting. Parallel box squat is currently tolerated; avoid unnecessary deep heavy back-squat exposure. Recurrent brachioradialis irritation history; manage pulling volume and grip intelligently.",
  sport:"BJJ/MMA, mostly BJJ",sport_schedule:[{"day":"Sun","intensity":"moderate"},{"day":"Mon","intensity":"moderate-hard"},{"day":"Tue","intensity":"hard"},{"day":"Wed","intensity":"moderate"},{"day":"Thu","intensity":"hard"}],
  notes:"REFERENCE CLIENT / COACH OWNER. Four strength sessions plus frequent grappling. Goal hierarchy is box squat strength/endurance, direct OAP skill, then strict OHP, while preserving mat performance. Direct OAP work must not be replaced by weighted chin-up support. Weighted chin strength is already elite, so trivial bodyweight pulling is not a primary strength prescription. Use a parallel box squat rather than deep heavy back squat. HSPU is optional/nice-to-have and lower priority than strict OHP and mat energy. Use low-fatigue Zone 2. Because sport plus lifting occupies most of the week, at least one gym day should be deliberately lower-cost/recovery-contingent. No junk volume."
};
function weekBlock(p,w){const m=p.match(new RegExp(`START_WEEK${w}_TSV\\n([\\s\\S]*?)\\nEND_WEEK${w}_TSV`));if(!m)throw new Error(`week ${w} missing`);return m[1];}
function rows(p){const out=[];for(const w of [1,2,3,4])for(const l of weekBlock(p,w).split("\n").slice(1)){if(!l.includes("\t"))continue;const c=l.split("\t");if(c.length===9)out.push({w,line:l,day:c[0],exercise:c[1]});}return out;}
async function build(){const started=Date.now();const a=await jf("/api/build",{method:"POST",body:JSON.stringify({intake})});if(!a.job_id)throw new Error("no job_id");console.log("raz_reference accepted",a.job_id);const end=Date.now()+12*60*1000;while(Date.now()<end){await sleep(2500);const j=await jf(`/api/job/${a.job_id}`);if(j.status==="done"){const program=j.program||"";fs.writeFileSync(`${outDir}/raz_reference.txt`,program);const rr=rows(program);const review=rr.filter(x=>/\[REVIEW\]|contact\s+support|could not be safely generated/i.test(x.line));if(review.length)throw new Error(`client-clean fail ${review.slice(0,5).map(x=>x.line).join(" || ")}`);for(const w of [1,2,3,4]){const days=[...new Set(weekBlock(program,w).split("\n").slice(1).map(l=>l.split("\t")[0]).filter(Boolean))];if(JSON.stringify(days)!==JSON.stringify(["Mon","Wed","Thu","Sat"]))throw new Error(`calendar fail week ${w}: ${JSON.stringify(days)}`);}const result={secs:Math.round((Date.now()-started)/100)/10,token:j.token,violations:j?._meta?.violations??null,length:program.length};fs.writeFileSync(`${outDir}/summary.json`,JSON.stringify(result,null,2));console.log("RESULT",JSON.stringify(result));console.log(`PROGRAM_BEGIN\n${program}\nPROGRAM_END`);return;}if(j.status==="error")throw new Error(j.error||"build error");}throw new Error("timeout");}
await waitDeploy();await build();