import fs from "node:fs";

// Warrior v5.2.2 client-ready rerun.
const BASE = process.env.LIVE_BASE || "https://raz-coaching-platform.onrender.com";
const outDir = "stress-output";
fs.mkdirSync(outDir, { recursive: true });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function jsonFetch(path, init = {}) { const res = await fetch(BASE + path,{...init,headers:{"Content-Type":"application/json",...(init.headers||{})}}); const text=await res.text(); let data; try{data=JSON.parse(text)}catch{data={raw:text}}; if(!res.ok) throw new Error(`${path} HTTP ${res.status}: ${text.slice(0,500)}`); return data; }
async function waitForDeployment(){ const deadline=Date.now()+10*60*1000; let last=null; while(Date.now()<deadline){ try{ last=await jsonFetch("/api/health"); console.log("health",JSON.stringify(last)); if(last?.ok&&last?.mode==="openai"&&/^gpt-/i.test(String(last?.model||""))&&last?.ai_configured!==false&&last?.openai_execution_path==="deterministic-skeleton-v5.2.2-warrior-clean") return last; }catch(e){ console.log("health wait:",e.message);} await sleep(5000);} throw new Error(`Live deployment did not report deterministic-skeleton-v5.2.2-warrior-clean in time. Last health: ${JSON.stringify(last)}`); }
const AVATARS={warrior_client:{primary_goals:["Build a Batman-style warrior physique: muscular, strong, athletic, explosive and capable","Hypertrophy with strong weighted calisthenics","Develop useful athletic skills, power, trunk strength, grip and work capacity"],secondary_goals:["Improve body composition while preserving strength","Make outdoor training challenging and enjoyable without gimmicky random circuits"],experience:"intermediate",days_per_week:"3",session_length:"60-75",bodyweight:"100 kg",height:"180 cm",equipment:"Outdoor calisthenics park with pull-up bar, parallel dip bars, gymnastic rings, and a weighted dip/pull-up belt with load plates allowing up to 37 kg added weight. No barbell, no dumbbells, no cables, no machines.",training_location:"outdoor_park",language:"en",split_preference:"coach_decide",current_numbers:"Weighted dip: +20 kg x12 reps and +35 kg x2 reps. Weighted pull-up: +20 kg x6 reps. Historical back squat around 100 kg, showing relatively strong legs, but no barbell is available now.",injuries:"none",sport:"none",sport_schedule:[],notes:"Real client. Overweight/chubby at about 100 kg but naturally strong. He does not train combat sports. He likes a Batman/warrior training identity. Translate that vibe into serious programming: hypertrophy, relative strength, weighted pull-ups and dips, athletic lower-body work, jumps or short sprints where appropriate, trunk, grip and structured conditioning. Do NOT turn warrior style into random burpees, bear crawls or meaningless AMRAP circus. Exactly two sessions are mandatory. The third weekly session must be explicitly OPTIONAL and lower-cost/recovery-contingent, so missing it does not break progression. Use unilateral lower-body methods, tempo, ROM and athletic power to overcome the 37 kg external-load ceiling. Respect the park-only equipment hard stop."}};
async function build(name,intake){const started=Date.now();const accepted=await jsonFetch("/api/build",{method:"POST",body:JSON.stringify({intake})});if(!accepted.job_id)throw new Error(`${name}: no job_id returned`);console.log(`${name}: accepted job ${accepted.job_id}`);const deadline=Date.now()+12*60*1000;while(Date.now()<deadline){await sleep(2500);const job=await jsonFetch(`/api/job/${accepted.job_id}`);if(job.status==="done"){const secs=Math.round((Date.now()-started)/100)/10;const program=job.program||"";if(/\[REVIEW\]|contact\s+support|could not be safely generated/i.test(program))throw new Error(`${name}: client-clean gate failed; review/support text survived`);const result={name,secs,token:job.token,violations:job?._meta?.violations??null,length:program.length,program};fs.writeFileSync(`${outDir}/${name}.txt`,program);console.log(`RESULT ${name}: ${secs}s, len=${program.length}, violations=${result.violations}`);console.log(`PROGRAM_BEGIN ${name}\n${program}\nPROGRAM_END ${name}`);return result;}if(job.status==="error")throw new Error(`${name}: ${job.error||"unknown build error"}`);}throw new Error(`${name}: timed out waiting for job`);}
const health=await waitForDeployment();const results=[];for(const [name,intake] of Object.entries(AVATARS))results.push(await build(name,intake));fs.writeFileSync(`${outDir}/summary.json`,JSON.stringify({health,results:results.map(({program,...r})=>r)},null,2));console.log("STRESS_SUMMARY",JSON.stringify({health,results:results.map(({program,...r})=>r)}));
