const BASE='https://raz-coaching-platform.onrender.com';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function req(path,options={}){const res=await fetch(BASE+path,options);const text=await res.text();let body=null;try{body=text?JSON.parse(text):null}catch{body={raw:text}}return{res,body,text};}
async function poll(id){const started=Date.now();while(Date.now()-started<420000){const x=await req('/api/job/'+id);if(x.body?.status==='done')return x.body;if(x.body?.status==='error')throw new Error(x.body.error||'build failed');await sleep(4000);}throw new Error('build timeout');}
const consent=()=>({health_data:true,policy_version:'2026-08-11',consented_at:new Date().toISOString()});
function weekRows(program,week=1){const m=String(program||'').match(new RegExp(`START_WEEK${week}_TSV\\s*\\n([\\s\\S]*?)\\nEND_WEEK${week}_TSV`,'i'));if(!m)return[];const lines=m[1].split('\n').filter(x=>x.trim());if(lines.length<2)return[];const h=lines[0].split('\t').map(x=>x.trim().toLowerCase());const i=Object.fromEntries(h.map((x,n)=>[x,n]));return lines.slice(1).map(line=>{const c=line.split('\t');return{day:c[i.day]||'',exercise:c[i.exercise]||'',weight:c[i.weight]||'',sets:c[i.sets]||'',reps:c[i.reps]||'',rest:c[i.rest]||'',rpe:c[i['target rpe']]||'',notes:c[i.notes]||'',raw:line};});}
function meaningful(r,re){if(/^\s*\[WARMUP\]/i.test(r.exercise)||!re.test(`${r.exercise} ${r.notes}`))return false;const d=`${r.reps} ${r.weight} ${r.notes}`;const sets=Math.max(1,Number(String(r.sets).match(/\d+/)?.[0]||1));const mins=[...d.matchAll(/(\d+(?:\.\d+)?)\s*(?:min|minutes?)\b/gi)].map(m=>Number(m[1]));return mins.some(x=>x>=15||x*sets>=15)||/\b\d+(?:\.\d+)?\s*(?:km|m)\b/i.test(d)||/\b\d+\s*(?:x|×)\s*\d+(?:\.\d+)?\s*(?:m|km|min|minutes?)\b/i.test(d);}
function modalityDays(rows,re){return new Set(rows.filter(r=>meaningful(r,re)).map(r=>r.day)).size;}
function progressionBearing(r){return /(?:interval|threshold|critical|race pace|goal pace|target pace|2k pace|3k pace|5k pace|10k pace|marathon pace|split|stroke rate|cadence|power target|pace target|progress|\b\d+:\d+(?:-\d+:\d+)?\s*\/\s*500m\b|\b\d+(?::\d+)?\s*\/\s*km\b|\b\d+(?:\.\d+)?\s*(?:km\/h|kph|watts?|w)\b)/i.test(`${r.exercise} ${r.weight} ${r.reps} ${r.rest} ${r.notes}`);}
function common(program){const rows=weekRows(program,1);const marker=Number((program.match(/QA_FORMULA_VIOLATION_COUNT:\s*(\d+)/)||[])[1]||0);const leakage=/\[REVIEW\]|contact support|placeholder|could not be safely generated|(?:RAZ BASE |ENDURANCE )?SOURCE EXCERPT\s*\d+/i.test(program);const sprintConflict=rows.some(r=>/^Sprint$/i.test(r.exercise)&&/(speed|velocity|90\s*[-–]\s*95%)/i.test(r.notes)&&!/^N\/?A$/i.test(String(r.rpe).trim()));return{rows,marker,leakage,sprintConflict};}
function strengthDays(rows){const conditioning=/\b(?:run|running|bike|cycling|swim|swimming|rower|rowing|zone-2|sprint|walk)\b/i;const s=new Set();for(const r of rows){if(/^\s*\[WARMUP\]/i.test(r.exercise)||conditioning.test(r.exercise))continue;if(/squat|lunge|deadlift|rdl|press|bench|row|chin|pull.?up|dip|curl|extension|raise|fly|pulldown|leg press|leg curl|hip thrust|split squat|step.?up|calf|planche|lever|handstand|muscle.?up/i.test(r.exercise))s.add(r.day);}return s.size;}
async function runCase(name,intake,check){const started=Date.now();const build=await req('/api/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({intake})});console.log(`\n===== ${name} BUILD =====\n${build.res.status} ${JSON.stringify(build.body)}`);if(build.res.status!==202||!build.body?.job_id||!build.body?.token)return{name,ok:false,error:`build not accepted: ${build.res.status} ${JSON.stringify(build.body)}`};const token=build.body.token;try{const done=await poll(build.body.job_id);const program=String(done.program||'');console.log(`${name} generation_seconds=${((Date.now()-started)/1000).toFixed(1)}`);console.log(`===== ${name} FULL PROGRAM START =====\n${program}\n===== ${name} FULL PROGRAM END =====`);const c=common(program);const checks=check(program,c);const ok=c.marker===0&&!c.leakage&&!c.sprintConflict&&checks.every(x=>x.ok);console.log(`${name} COMMON formula_marker=${c.marker} leakage=${c.leakage} sprint_rpe_conflict=${c.sprintConflict}`);for(const x of checks)console.log(`${name} CHECK ${x.ok?'PASS':'FAIL'} ${x.name}: ${x.detail}`);return{name,ok,program,checks,...c};}catch(e){console.log(`${name} ERROR=${String(e?.stack||e)}`);return{name,ok:false,error:String(e?.message||e)};}finally{const del=await req('/api/client-data',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})}).catch(()=>null);console.log(`${name} delete_status=${del?.res?.status||'failed'}`);}}

const cfg=await req('/api/program-pass-config');console.log('CONFIG',cfg.res.status,JSON.stringify(cfg.body));if(cfg.res.status!==200||cfg.body?.enforced!==false)throw new Error('Program Pass enforcement must be OFF for live QA.');

// Zero-cost clarification probe: no job/token should exist because generation is never entered.
const ambiguous={primary_goals:['Back squat 200 kg'],current_numbers:'Back squat 170 kg x 3',injuries:'Recurring low-back irritation',days_per_week:3,session_length:'60 minutes',equipment:'Full commercial gym',training_location:'commercial_gym',language:'en',privacy_consent:consent()};
const clarification=await req('/api/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({intake:ambiguous})});
const clarifyOk=clarification.res.status===422&&clarification.body?.clarification_required===true&&!clarification.body?.job_id&&!clarification.body?.token;
console.log('CLARIFICATION_GATE',clarification.res.status,JSON.stringify(clarification.body),'no_generation_job='+clarifyOk);if(!clarifyOk)throw new Error('Clarification gate did not stop before generation/job creation.');

const avatar3={primary_goals:['Build a Warrior / Batman performance profile: muscular, strong, athletic, explosive and capable'],secondary_goals:['Improve weighted pull-up and weighted dip strength and hypertrophy','Build lower-body strength, trunk strength, grip, work capacity and body composition'],maintenance_goals:[],goal_priority_model:'tiered_equal_primary',experience:'intermediate-advanced',days_per_week:3,gym_availability_mode:'limited',available_gym_days:['Mon','Thu','Sat'],same_day_gap_hours:0,session_length:'60 minutes',bodyweight:'100 kg',height:'180 cm',equipment:'Outdoor park only: pull-up bar, parallel bars, rings, weighted belt and plates with maximum external load about 37 kg, and open ground. No barbell, no dumbbells, no machines, no cables, no bike, no rower, no box.',training_location:'outdoor_park',language:'en',split_preference:'coach_decide',current_numbers:'Weighted Dip: +20 kg x 12; Weighted Dip: +35 kg x 2; Weighted Pull-Up: +20 kg x 6; historical squat about 100 kg but no current barbell access.',performance_markers:['Weighted Dip: +20 kg x 12','Weighted Dip: +35 kg x 2','Weighted Pull-Up: +20 kg x 6','Historical squat about 100 kg'],injuries:'No current injury reported.',pain:{active:false,description:''},mobility:{active:false,limitation:''},sport:'',sport_schedule:[],sleep_hours:'7-8 hours',recovery_rating:'Average',notes:'Monday and Thursday are mandatory progression sessions. Saturday is optional, but OPTIONAL DOES NOT MEAN EASY: it must be productive, stimulating and useful while the core program must still progress if Saturday is skipped. Avoid random burpees, bear crawls, circus AMRAPs or CrossFit-style randomness. Build useful weighted calisthenics, hypertrophy, lower-body strength, trunk, grip, athletic power and work capacity within the listed equipment.',privacy_consent:consent()};
const annoying={primary_goals:['Back squat 200 kg','Weighted chin-up +70 kg for 3 reps'],secondary_goals:['Improve 5 km from 25:00 to 22:30'],maintenance_goals:[],goal_priority_model:'tiered_equal_primary',experience:'advanced',days_per_week:4,gym_availability_mode:'flexible',available_gym_days:[],same_day_gap_hours:6,session_length:'60 minutes',bodyweight:'84 kg',equipment:'Full commercial gym — all standard barbells, dumbbells, racks, machines, cables, cardio machines and bodyweight stations available.',training_location:'commercial_gym',language:'en',split_preference:'coach_decide',current_numbers:'Back squat: 170 kg x 3\nWeighted chin-up: +55 kg x 3\nRDL: 190 kg x 5\nOHP: 70 kg x 5\n5 km: 25:00',performance_markers:['Back squat: 170 kg x 3','Weighted chin-up: +55 kg x 3','RDL: 190 kg x 5','OHP: 70 kg x 5','5 km: 25:00'],injuries:'Mild recurring low-back irritation after high-volume deep squatting; controlled box squats and RDLs are currently tolerated.',pain:{active:true,description:'Mild recurring low-back irritation after high-volume deep squatting',severity:'mild',character:'ache/tightness',next_day_baseline:'usually back to baseline',tolerated_movements:'controlled box squats, RDLs, split squats'},mobility:{active:false,limitation:''},sport:'MMA / BJJ',sport_schedule:[{day:'Mon',intensity:'hard',gap_hours:6},{day:'Wed',intensity:'moderate',gap_hours:6},{day:'Fri',intensity:'hard',gap_hours:6},{day:'Sat',intensity:'moderate',gap_hours:6}],sleep_hours:'6.5',recovery_rating:'average / variable',notes:'Currently running 2 sessions per week, about 10 km/week. Avoid hard conditioning within 24 hours before hard MMA. Keep sessions at or under 60 minutes. No more than two genuinely hard lower-body sessions per week. Four strength sessions are requested, but low-cost resistance/accessory sessions are acceptable when sport load is high; do not silently replace a strength day with cardio-only work.',privacy_consent:consent()};
const runner={primary_goals:['Improve 5 km from 25:00 to 22:30'],secondary_goals:['Maintain whole-body strength'],maintenance_goals:[],goal_priority_model:'tiered_equal_primary',experience:'intermediate',days_per_week:2,gym_availability_mode:'flexible',available_gym_days:[],session_length:'70 minutes',bodyweight:'76 kg',equipment:'Commercial gym, treadmill, outdoor track and road running routes.',training_location:'commercial_gym',language:'en',split_preference:'coach_decide',current_numbers:'5 km: 25:00; Back squat: 110 kg x 5; Pull-up: 10 strict reps',performance_markers:['5 km: 25:00','Back squat: 110 kg x 5'],injuries:'No current injury.',pain:{active:false,description:''},sport:'Running',sport_schedule:[{day:'Tue',modality:'running',intensity:'quality'},{day:'Thu',modality:'running',intensity:'easy'},{day:'Sun',modality:'running',intensity:'easy-long'}],sleep_hours:'7.5',recovery_rating:'good',notes:'Currently runs 3 times per week, about 20 km/week. Recent 5K is 25:00. Preserve three running exposures. Goal is 22:30, but training pace must be calibrated from current performance rather than assuming goal pace is currently sustainable.',privacy_consent:consent()};
const rower={primary_goals:['Improve 2 km rowing ergometer from 7:30 to 7:05'],secondary_goals:['Maintain whole-body strength'],maintenance_goals:[],goal_priority_model:'tiered_equal_primary',experience:'intermediate-advanced',days_per_week:2,gym_availability_mode:'flexible',available_gym_days:[],session_length:'70 minutes',bodyweight:'82 kg',equipment:'Concept2 rowing ergometer and full commercial gym.',training_location:'commercial_gym',language:'en',split_preference:'coach_decide',current_numbers:'2 km rowing ergometer: 7:30; Back squat: 130 kg x 5; Bench press: 90 kg x 5',performance_markers:['2 km row: 7:30','Back squat: 130 kg x 5'],injuries:'No current injury.',pain:{active:false,description:''},sport:'Rowing',sport_schedule:[{day:'Mon',modality:'rowing',intensity:'easy'},{day:'Wed',modality:'rowing',intensity:'quality'},{day:'Sat',modality:'rowing',intensity:'moderate'}],sleep_hours:'8',recovery_rating:'good',notes:'Currently rows 3 times per week. Use rowing-specific pace/power and stroke-rate logic where supported; do not prescribe short intervals from heart rate alone.',privacy_consent:consent()};
const marathon={primary_goals:['Improve marathon from 4:05 to 3:40'],secondary_goals:['Maintain basic strength and stay durable'],maintenance_goals:[],goal_priority_model:'tiered_equal_primary',experience:'intermediate',days_per_week:1,gym_availability_mode:'flexible',available_gym_days:[],session_length:'90 minutes',bodyweight:'70 kg',equipment:'Road running routes, treadmill and commercial gym.',training_location:'commercial_gym',language:'en',split_preference:'coach_decide',current_numbers:'Marathon: 4:05; recent half marathon: 1:50; Back squat: 85 kg x 5',performance_markers:['Marathon: 4:05','Half marathon: 1:50','Back squat: 85 kg x 5'],injuries:'No current injury.',pain:{active:false,description:''},sport:'Running',sport_schedule:[{day:'Tue',modality:'running',intensity:'quality'},{day:'Thu',modality:'running',intensity:'easy'},{day:'Sat',modality:'running',intensity:'easy'},{day:'Sun',modality:'running',intensity:'long'}],sleep_hours:'7.5',recovery_rating:'good',notes:'Currently runs 4 times per week, about 38 km/week. Longest recent run is 22 km. Goal is a future 3:40 marathon, but do not assume goal marathon pace is immediately sustainable for large doses. Preserve four run exposures and progress conservatively from current volume/performance.',privacy_consent:consent()};
const triathlon={primary_goals:['Improve Olympic-distance triathlon performance across 1.5 km swim, 40 km bike and 10 km run'],secondary_goals:['Maintain basic whole-body strength'],maintenance_goals:[],goal_priority_model:'tiered_equal_primary',experience:'intermediate',days_per_week:2,gym_availability_mode:'flexible',available_gym_days:[],same_day_gap_hours:6,session_length:'75 minutes',bodyweight:'72 kg',equipment:'Pool access, road bike with power meter, indoor bike trainer, outdoor running routes and a commercial gym.',training_location:'commercial_gym',language:'en',split_preference:'coach_decide',current_numbers:'1.5 km swim: 32:00; 40 km bike: 1:20:00; 10 km run: 52:00; Back squat: 90 kg x 5',performance_markers:['1.5 km swim: 32:00','40 km bike: 1:20:00','10 km run: 52:00','Back squat: 90 kg x 5'],injuries:'No current injury reported.',pain:{active:false,description:''},mobility:{active:false,limitation:''},sport:'Triathlon',sport_schedule:[{day:'Mon',modality:'swimming',intensity:'easy'},{day:'Tue',modality:'cycling',intensity:'moderate'},{day:'Wed',modality:'running',intensity:'moderate'},{day:'Thu',modality:'swimming',intensity:'moderate'},{day:'Fri',modality:'cycling',intensity:'easy'},{day:'Sun',modality:'running',intensity:'easy'}],sleep_hours:'8',recovery_rating:'good',notes:'Currently trains 2 swims, 2 rides and 2 runs each week. Bike has direct power data but no FTP value is supplied, so do not invent watts. Keep separate modality-specific intensity anchors and avoid pretending one pace or heart-rate zone transfers exactly across swim, bike and run. Two gym strength sessions are available for maintenance.',privacy_consent:consent()};

const RUN=/\b(?:Run|Running|Treadmill|Zone-2 Run|Shuttle Run)\b/i, ROW=/\b(?:Row|Rower|Rowing|Rowing Ergometer|Zone-2 Row)\b/i, SWIM=/\b(?:Swim|Swimming|Pool)\b/i, BIKE=/\b(?:Bike|Cycling|Cycle|Zone-2 Bike)\b/i;
const results=[];
results.push(await runCase('AVATAR3_WARRIOR',avatar3,(p,c)=>[{name:'mandatory_days_present',ok:/\bMon\b/i.test(c.rows.map(r=>r.day).join(' '))&&/\bThu\b/i.test(c.rows.map(r=>r.day).join(' ')),detail:'Mon/Thu required'},{name:'weighted_pull_and_dip',ok:c.rows.some(r=>/Weighted Pull-up/i.test(r.exercise))&&c.rows.some(r=>/Weighted Dip/i.test(r.exercise)),detail:'direct weighted calisthenics'},{name:'optional_satellite_productive',ok:c.rows.some(r=>/Sat/i.test(r.day)&&!/\[WARMUP\]/i.test(r.exercise)),detail:'Saturday contains real work'}]));
results.push(await runCase('ANNOYING_CONCURRENT',annoying,(p,c)=>{const direct=c.rows.some(r=>/^Back Squat$/i.test(r.exercise));const box=c.rows.some(r=>/^Box Squat(?: to Parallel)?$/i.test(r.exercise));const painAware=direct||(box&&/(low[- ]?back|lumbar|irrit|deep|depth|toler|range|rom)/i.test(p));const fixedBox=c.rows.some(r=>/^Box Squat(?: to Parallel)?$/i.test(r.exercise)&&/\d+(?:\.\d+)?\s*kg/i.test(r.weight));const runDays=modalityDays(c.rows,RUN);return[{name:'pain_aware_squat_specificity',ok:painAware,detail:`direct=${direct} box=${box}`},{name:'unbenchmarked_box_no_fixed_kg',ok:!fixedBox,detail:`fixedBoxKg=${fixedBox}`},{name:'weighted_chin_specificity',ok:c.rows.some(r=>/^Weighted Chin-up$/i.test(r.exercise)),detail:'direct weighted chin'},{name:'four_strength_days',ok:strengthDays(c.rows)>=4,detail:`strength days=${strengthDays(c.rows)}`},{name:'two_runs_preserved',ok:runDays>=2,detail:`run days=${runDays}`},{name:'5k_progression',ok:c.rows.some(r=>meaningful(r,RUN)&&progressionBearing(r)),detail:'progression-bearing run'}];}));
results.push(await runCase('RUNNER_5K',runner,(p,c)=>{const days=modalityDays(c.rows,RUN);return[{name:'three_runs_preserved',ok:days>=3,detail:`run days=${days}`},{name:'progression_session',ok:c.rows.some(r=>meaningful(r,RUN)&&progressionBearing(r)),detail:'event progression'},{name:'two_strength_days',ok:strengthDays(c.rows)>=2,detail:`strength days=${strengthDays(c.rows)}`}];}));
results.push(await runCase('ROWER_2K',rower,(p,c)=>{const days=modalityDays(c.rows,ROW);return[{name:'three_rows_preserved',ok:days>=3,detail:`row days=${days}`},{name:'split_or_power_progression',ok:c.rows.some(r=>meaningful(r,ROW)&&progressionBearing(r)),detail:'row-specific progression'},{name:'two_strength_days',ok:strengthDays(c.rows)>=2,detail:`strength days=${strengthDays(c.rows)}`}];}));
results.push(await runCase('MARATHON',marathon,(p,c)=>{const days=modalityDays(c.rows,RUN);const longest=c.rows.filter(r=>meaningful(r,RUN)).some(r=>/long|duration|aerobic|marathon/i.test(`${r.exercise} ${r.notes}`));return[{name:'four_runs_preserved',ok:days>=4,detail:`run days=${days}`},{name:'progression_session',ok:c.rows.some(r=>meaningful(r,RUN)&&progressionBearing(r)),detail:'progression-bearing run'},{name:'long_run_role',ok:longest,detail:'long/aerobic specific work'},{name:'strength_maintenance',ok:strengthDays(c.rows)>=1,detail:`strength days=${strengthDays(c.rows)}`}];}));
results.push(await runCase('TRIATHLON_OLYMPIC',triathlon,(p,c)=>{const sd=modalityDays(c.rows,SWIM),bd=modalityDays(c.rows,BIKE),rd=modalityDays(c.rows,RUN);return[{name:'two_swims',ok:sd>=2,detail:`swim days=${sd}`},{name:'two_bikes',ok:bd>=2,detail:`bike days=${bd}`},{name:'two_runs',ok:rd>=2,detail:`run days=${rd}`},{name:'modality_specific_progression',ok:c.rows.some(r=>meaningful(r,SWIM)&&progressionBearing(r))&&c.rows.some(r=>meaningful(r,BIKE)&&progressionBearing(r))&&c.rows.some(r=>meaningful(r,RUN)&&progressionBearing(r)),detail:'progression across all 3 modes'},{name:'two_strength_days',ok:strengthDays(c.rows)>=2,detail:`strength days=${strengthDays(c.rows)}`}];}));

console.log('\n===== FINAL SIX ACCEPTANCE SUMMARY =====');for(const r of results)console.log(JSON.stringify({name:r.name,ok:r.ok,marker:r.marker,leakage:r.leakage,sprintConflict:r.sprintConflict,error:r.error||null,failed:(r.checks||[]).filter(x=>!x.ok).map(x=>x.name)}));if(results.some(r=>!r.ok)){console.log('FINAL_SIX_ACCEPTANCE=FAIL');process.exitCode=1}else console.log('FINAL_SIX_ACCEPTANCE=PASS');
