import fs from "node:fs";

// Final Warrior client QA: park-only equipment, Mon/Thu mandatory, Sat optional.
const BASE = process.env.LIVE_BASE || "https://raz-coaching-platform.onrender.com";
const outDir = "stress-output";
fs.mkdirSync(outDir, { recursive: true });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function jsonFetch(path, init = {}) { const res = await fetch(BASE + path,{...init,headers:{"Content-Type":"application/json",...(init.headers||{})}}); const text=await res.text(); let data; try{data=JSON.parse(text)}catch{data={raw:text}}; if(!res.ok) throw new Error(`${path} HTTP ${res.status}: ${text.slice(0,500)}`); return data; }
async function waitForDeployment(){ const deadline=Date.now()+10*60*1000; let last=null; while(Date.now()<deadline){ try{ last=await jsonFetch("/api/health"); console.log("health",JSON.stringify(last)); if(last?.ok&&last?.mode==="openai"&&/^gpt-/i.test(String(last?.model||""))&&last?.ai_configured!==false&&last?.openai_execution_path==="deterministic-skeleton-v5.2.4-warrior-park") return last; }catch(e){ console.log("health wait:",e.message);} await sleep(5000);} throw new Error(`Live deployment did not report deterministic-skeleton-v5.2.4-warrior-park in time. Last health: ${JSON.stringify(last)}`); }
const AVATARS={warrior_client:{primary_goals:["Build a Batman-style warrior physique: muscular, strong, athletic, explosive and capable","Hypertrophy with strong weighted calisthenics","Develop useful athletic skills, power, trunk strength, grip and work capacity"],secondary_goals:["Improve body composition while preserving strength","Make outdoor training challenging and enjoyable without gimmicky random circuits"],experience:"intermediate",days_per_week:"3",available_gym_days:["Mon","Thu","Sat"],session_length:"60-75",bodyweight:"100 kg",height:"180 cm",equipment:"Outdoor calisthenics park with pull-up bar, parallel dip bars, gymnastic rings, weighted dip/pull-up belt with load plates allowing up to 37 kg added weight, and flat open park/grass space for short sprints. No box, no bench, no barbell, no dumbbells, no cables, no bike, no rower, no machines.",training_location:"outdoor_park",language:"en",split_preference:"coach_decide",current_numbers:"Weighted dip: +20 kg x12 reps and +35 kg x2 reps. Weighted pull-up: +20 kg x6 reps. Historical back squat around 100 kg, showing relatively strong legs, but no barbell is available now.",injuries:"none",sport:"none",sport_schedule:[],notes:"REAL CLIENT. Overweight/chubby at about 100 kg but naturally strong. Batman/warrior identity means serious hypertrophy, relative strength, explosive athleticism, useful movement skill, trunk/grip and work capacity — not random circuits. MONDAY and THURSDAY are MANDATORY progression sessions. SATURDAY is explicitly OPTIONAL and lower-cost; missing Saturday must not break progress. Park-only hard stop: pull-up bar, parallel bars, rings, belt up to 37 kg, and open ground only. No box jumps. For power use Broad Jump, Split Squat Jump, pogo-style ground contacts if an approved name exists, or short maximal sprints with full recovery. No bike/rower/machine cardio; use brisk walking/easy jogging for Zone 2. Use unilateral lower-body loading, tempo, pauses and ROM to overcome the external-load ceiling. Respect weighted pull-up and dip benchmarks exactly."}};
async function build(name,intake){const started=Date.now();const accepted=await jsonFetch("/api/build",{method:"POST",body:JSON.stringify({intake})});if(!accepted.job_id)throw new Error(`${name}: no job_id returned`);console.log(`${name}: accepted job ${accepted.job_id}`);const deadline=Date.now()+12*60*1000;while(Date.now()<deadline){await sleep(2500);const job=await jsonFetch(`/api/job/${accepted.job_id}`);if(job.status==="done"){const secs=Math.round((Date.now()-started)/100)/10;const program=job.program||"";if(/\[REVIEW\]|contact\s+support|could not be safely generated/i.test(program))throw new Error(`${name}: client-clean gate failed; review/support text survived`);if(/\bBox Jump\b|Zone-2 Bike|Zone-2 Row|Assault Bike|Rower/i.test(program))throw new Error(`${name}: park-only equipment gate failed`);for(const wk of [1,2,3,4]){const m=program.match(new RegExp(`START_WEEK${wk}_TSV\\n([\\s\\S]*?)\\nEND_WEEK${wk}_TSV`));if(!m)throw new Error(`${name}: week ${wk} missing`);const days=[...new Set(m[1].split("\n").slice(1).map(l=>l.split("\t")[0]).filter(Boolean))];if(JSON.stringify(days)!==JSON.stringify(["Mon","Thu","Sat"]))throw new Error(`${name}: calendar gate failed week ${wk}: ${JSON.stringify(days)}`);}const result={name,secs,token:job.token,violations:job?._meta?.violations??null,length:program.length,program};fs.writeFileSync(`${outDir}/${name}.txt`,program);console.log(`RESULT ${name}: ${secs}s, len=${program.length}, violations=${result.violations}`);console.log(`PROGRAM_BEGIN ${name}\n${program}\nPROGRAM_END ${name}`);return result;}if(job.status==="error")throw new Error(`${name}: ${job.error||"unknown build error"}`);}throw new Error(`${name}: timed out waiting for job`);}
const health=await waitForDeployment();const results=[];for(const [name,intake] of Object.entries(AVATARS))results.push(await build(name,intake));fs.writeFileSync(`${outDir}/summary.json`,JSON.stringify({health,results:results.map(({program,...r})=>r)},null,2));console.log("STRESS_SUMMARY",JSON.stringify({health,results:results.map(({program,...r})=>r)}));
