const BASE='https://raz-coaching-platform.onrender.com';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function req(path,options={}){const res=await fetch(BASE+path,options);const text=await res.text();let body=null;try{body=text?JSON.parse(text):null}catch{body={raw:text}}return{res,body,text};}
async function poll(id){const started=Date.now();while(Date.now()-started<420000){const x=await req('/api/job/'+id);if(x.body?.status==='done')return x.body;if(x.body?.status==='error')throw new Error(x.body.error||'build failed');await sleep(4000);}throw new Error('build timeout');}
const consent=()=>({health_data:true,policy_version:'2026-08-11',consented_at:new Date().toISOString()});
function weekRows(program,week=1){const m=String(program||'').match(new RegExp(`START_WEEK${week}_TSV\\s*\\n([\\s\\S]*?)\\nEND_WEEK${week}_TSV`,'i'));if(!m)return[];const lines=m[1].split('\n').filter(x=>x.trim());if(lines.length<2)return[];const h=lines[0].split('\t').map(x=>x.trim().toLowerCase());const i=Object.fromEntries(h.map((x,n)=>[x,n]));return lines.slice(1).map(line=>{const c=line.split('\t');return{day:c[i.day]||'',exercise:c[i.exercise]||'',weight:c[i.weight]||'',sets:c[i.sets]||'',reps:c[i.reps]||'',rest:c[i.rest]||'',rpe:c[i['target rpe']]||'',notes:c[i.notes]||'',raw:line};});}
function meaningful(r,re){if(/^\s*\[WARMUP\]/i.test(r.exercise)||!re.test(`${r.exercise} ${r.notes}`))return false;const d=`${r.reps} ${r.weight} ${r.notes}`;const mins=[...d.matchAll(/(\d+(?:\.\d+)?)\s*(?:min|minutes?)\b/gi)].map(m=>Number(m[1]));return mins.some(x=>x>=15)||/\b\d+(?:\.\d+)?\s*(?:km|m)\b/i.test(d)||/\b\d+\s*(?:x|×)\s*\d+(?:\.\d+)?\s*(?:m|km|min|minutes?)\b/i.test(d);}
function modalityDays(rows,re){return new Set(rows.filter(r=>meaningful(r,re)).map(r=>r.day)).size;}
function progressionText(r){return `${r.exercise} ${r.weight} ${r.reps} ${r.rest} ${r.notes}`;}
function progressionBearing(r){return /(?:interval|threshold|critical|race pace|goal pace|target pace|2k pace|3k pace|5k pace|10k pace|marathon pace|split|stroke rate|cadence|power target|pace target|progress|\b\d+:\d+(?:-\d+:\d+)?\s*\/\s*500m\b|\b\d+(?::\d+)?\s*\/\s*km\b|\b\d+(?:\.\d+)?\s*(?:km\/h|kph|watts?|w)\b)/i.test(progressionText(r));}
function common(program){const rows=weekRows(program,1);return{rows,marker:Number((program.match(/QA_FORMULA_VIOLATION_COUNT:\s*(\d+)/)||[])[1]||0),leakage:/\[REVIEW\]|contact support|placeholder|could not be safely generated/i.test(program),sprintConflict:rows.some(r=>/^Sprint$/i.test(r.exercise)&&/(speed|velocity|90\s*[-–]\s*95%)/i.test(r.notes)&&!/^N\/?A$/i.test(String(r.rpe).trim()))};}
function strengthDayCount(rows){const conditioning=/\b(?:run|running|bike|cycling|swim|swimming|rower|rowing|zone-2|sprint|walk)\b/i;const days=new Set();for(const r of rows){if(/^\s*\[WARMUP\]/i.test(r.exercise)||conditioning.test(r.exercise))continue;days.add(r.day);}return days.size;}
async function runCase(name,intake,check){const build=await req('/api/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({intake})});console.log(`\n===== ${name} BUILD =====\n${build.res.status} ${JSON.stringify(build.body)}`);if(build.res.status!==202||!build.body?.job_id||!build.body?.token)return{name,ok:false,error:`build not accepted: ${build.res.status} ${JSON.stringify(build.body)}`};const token=build.body.token;try{const done=await poll(build.body.job_id);const program=String(done.program||'');console.log(`===== ${name} FULL PROGRAM START =====\n${program}\n===== ${name} FULL PROGRAM END =====`);const c=common(program);const checks=check(program,c);const ok=c.marker===0&&!c.leakage&&!c.sprintConflict&&checks.every(x=>x.ok);console.log(`${name} COMMON formula_marker=${c.marker} leakage=${c.leakage} sprint_rpe_conflict=${c.sprintConflict}`);for(const x of checks)console.log(`${name} CHECK ${x.ok?'PASS':'FAIL'} ${x.name}: ${x.detail}`);return{name,ok,program,checks,...c};}catch(e){console.log(`${name} ERROR=${String(e?.stack||e)}`);return{name,ok:false,error:String(e?.message||e)};}finally{const del=await req('/api/client-data',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})}).catch(()=>null);console.log(`${name} delete_status=${del?.res?.status||'failed'}`);}}

const cfg=await req('/api/program-pass-config');console.log('CONFIG',cfg.res.status,JSON.stringify(cfg.body));if(cfg.res.status!==200||cfg.body?.enforced!==false)throw new Error('Program Pass enforcement must be OFF for live QA.');

const annoying={primary_goals:['Back squat 200 kg','Weighted chin-up +70 kg for 3 reps'],secondary_goals:['Improve 5 km from 25:00 to 22:30'],maintenance_goals:[],goal_priority_model:'tiered_equal_primary',experience:'advanced',days_per_week:4,gym_availability_mode:'flexible',available_gym_days:[],same_day_gap_hours:6,session_length:'60 minutes',bodyweight:'84 kg',equipment:'Full commercial gym — all standard barbells, dumbbells, racks, machines, cables, cardio machines and bodyweight stations available.',training_location:'commercial_gym',language:'en',split_preference:'coach_decide',current_numbers:'Back squat: 170 kg x 3\nWeighted chin-up: +55 kg x 3\nRDL: 190 kg x 5\nOHP: 70 kg x 5\n5 km: 25:00',performance_markers:['Back squat: 170 kg x 3','Weighted chin-up: +55 kg x 3','RDL: 190 kg x 5','OHP: 70 kg x 5','5 km: 25:00'],injuries:'Mild recurring low-back irritation after high-volume deep squatting; controlled box squats and RDLs are currently tolerated.',pain:{active:true,description:'Mild recurring low-back irritation after high-volume deep squatting',severity:'mild',character:'ache/tightness',next_day_baseline:'usually back to baseline',tolerated_movements:'controlled box squats, RDLs, split squats'},mobility:{active:false,limitation:''},sport:'MMA / BJJ',sport_schedule:[{day:'Mon',intensity:'hard',gap_hours:6},{day:'Wed',intensity:'moderate',gap_hours:6},{day:'Fri',intensity:'hard',gap_hours:6},{day:'Sat',intensity:'moderate',gap_hours:6}],sleep_hours:'6.5',recovery_rating:'average / variable',notes:'Currently running 2 sessions per week, about 10 km/week. Avoid hard conditioning within 24 hours before hard MMA. Keep sessions at or under 60 minutes. No more than two genuinely hard lower-body sessions per week. Four strength sessions are requested, but low-cost resistance/accessory sessions are acceptable when sport load is high; do not silently replace a strength day with cardio-only work.',privacy_consent:consent()};
const triathlon={primary_goals:['Improve Olympic-distance triathlon performance across 1.5 km swim, 40 km bike and 10 km run'],secondary_goals:['Maintain basic whole-body strength'],maintenance_goals:[],goal_priority_model:'tiered_equal_primary',experience:'intermediate',days_per_week:2,gym_availability_mode:'flexible',available_gym_days:[],same_day_gap_hours:6,session_length:'75 minutes',bodyweight:'72 kg',equipment:'Pool access, road bike with power meter, indoor bike trainer, outdoor running routes and a commercial gym.',training_location:'commercial_gym',language:'en',split_preference:'coach_decide',current_numbers:'1.5 km swim: 32:00; 40 km bike: 1:20:00; 10 km run: 52:00; Back squat: 90 kg x 5',performance_markers:['1.5 km swim: 32:00','40 km bike: 1:20:00','10 km run: 52:00','Back squat: 90 kg x 5'],injuries:'No current injury reported.',pain:{active:false,description:''},mobility:{active:false,limitation:''},sport:'Triathlon',sport_schedule:[{day:'Mon',modality:'swimming',intensity:'easy'},{day:'Tue',modality:'cycling',intensity:'moderate'},{day:'Wed',modality:'running',intensity:'moderate'},{day:'Thu',modality:'swimming',intensity:'moderate'},{day:'Fri',modality:'cycling',intensity:'easy'},{day:'Sun',modality:'running',intensity:'easy'}],sleep_hours:'8',recovery_rating:'good',notes:'Currently trains 2 swims, 2 rides and 2 runs each week. Bike has direct power data. Program must keep separate modality-specific intensity anchors and avoid pretending one pace or heart-rate zone transfers exactly across swim, bike and run. Two gym strength sessions are available for maintenance.',privacy_consent:consent()};

const RUN=/\b(?:Run|Running|Treadmill|Zone-2 Run|Shuttle Run)\b/i;
const SWIM=/\b(?:Swim|Swimming|Pool)\b/i;
const BIKE=/\b(?:Bike|Cycling|Cycle|Zone-2 Bike)\b/i;
const results=[];
results.push(await runCase('ANNOYING_CONCURRENT',annoying,(program,c)=>{const direct=c.rows.some(r=>/^Back Squat$/i.test(r.exercise));const box=c.rows.some(r=>/^Box Squat(?: to Parallel)?$/i.test(r.exercise));const painAware=direct||(box&&/(low[- ]?back|lumbar|irrit|deep|depth|toler|range|rom)/i.test(program));const badBox=c.rows.some(r=>/^Box Squat(?: to Parallel)?$/i.test(r.exercise)&&/\d+(?:\.\d+)?\s*kg/i.test(r.weight));const runDays=modalityDays(c.rows,RUN);const runProgress=c.rows.some(r=>meaningful(r,RUN)&&progressionBearing(r));const chin=c.rows.some(r=>/^Weighted Chin-up$/i.test(r.exercise));const strengthDays=strengthDayCount(c.rows);return[{name:'pain_aware_squat_specificity',ok:painAware,detail:`direct=${direct} box=${box}`},{name:'unbenchmarked_box_no_fixed_kg',ok:!badBox,detail:`badBoxKg=${badBox}`},{name:'weighted_chin_specificity',ok:chin,detail:`weighted chin=${chin}`},{name:'four_strength_days',ok:strengthDays>=4,detail:`strength days=${strengthDays}`},{name:'existing_two_runs_preserved',ok:runDays>=2,detail:`run days=${runDays}`},{name:'5k_progression_present',ok:runProgress,detail:`progression=${runProgress}`}];}));
results.push(await runCase('TRIATHLON_OLYMPIC',triathlon,(program,c)=>{const swimDays=modalityDays(c.rows,SWIM),bikeDays=modalityDays(c.rows,BIKE),runDays=modalityDays(c.rows,RUN);const separateAnchors=/(swim[^\n]*(?:pace|stroke|rpe)|bike[^\n]*(?:power|watts|pace|rpe)|run[^\n]*(?:pace|rpe))/i.test(program);return[{name:'two_swims_preserved',ok:swimDays>=2,detail:`swim days=${swimDays}`},{name:'two_bikes_preserved',ok:bikeDays>=2,detail:`bike days=${bikeDays}`},{name:'two_runs_preserved',ok:runDays>=2,detail:`run days=${runDays}`},{name:'separate_modality_anchors',ok:separateAnchors,detail:`anchor evidence=${separateAnchors}`}];}));
console.log('\n===== REMAINING LIVE ACCEPTANCE SUMMARY =====');for(const r of results)console.log(JSON.stringify({name:r.name,ok:r.ok,marker:r.marker,leakage:r.leakage,sprintConflict:r.sprintConflict,error:r.error||null,failed:(r.checks||[]).filter(x=>!x.ok).map(x=>x.name)}));if(results.some(r=>!r.ok)){console.log('REMAINING_LIVE_ACCEPTANCE=FAIL');process.exitCode=1}else console.log('REMAINING_LIVE_ACCEPTANCE=PASS');
