// engine/v91_timeline_integrity.js
//
// A program may not contradict itself.
//
// The fight camp shipped two views of the same week. The week table labelled
// Friday "Day -1", which puts the fight on Saturday. The camp schedule, printed
// a few lines above it, gave the same athlete moderate MMA on that Saturday and
// light MMA on the Sunday: training on fight day, and training after the fight.
// Both were generated by this engine, in one file, and nothing looked.
//
// The coach's verdict was that the science was mostly fine and the failure was
// output integrity -- which is exactly right, and it is a different kind of
// defect from the ones the other rules catch. Every other validator asks
// whether a prescription is good coaching. This one asks whether the document
// agrees with itself, because a program that says two different things about
// the same day is not a program the athlete can follow, however sound either
// half is on its own.
//
// Three questions, two of them named by the coach:
//   - does any session fall on or after Day 0?
//   - do the calendar and the week table agree about which days carry work?
//   - does combat load actually come down into the event week?

import { parseWeek } from './v34_workload_accounting.js';
import { STATE, stateForWeek, competitionProfile, eventNoun } from './v68_competition_state.js';
import { eventWeekday } from './v77_fight_week_clock.js';
import { sportTaperPlan, renderCampSchedule, workingDaysByWeek } from './v78_sport_taper.js';

const WEEKDAYS = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
const LABEL = { mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun' };

function isWarmup(n) { return /^\s*\[WARMUP\]/i.test(String(n || '')); }
function dayKey(d) {
  const s = String(d || '').trim().toLowerCase().slice(0, 3);
  return WEEKDAYS.includes(s) ? s : null;
}

function eventWeek(intake, now) {
  if (!competitionProfile(intake, now)) return 0;
  for (let week = 1; week <= 4; week += 1) {
    if (stateForWeek(intake, week, now) === STATE.COMPETITION_WEEK) return week;
  }
  return 0;
}

// Weekdays that carry prescribed work in a week's table, inheriting the day
// down continuation rows the way every other clock rule in the engine reads it.
export function workingDaysOf(program, week) {
  const parsed = parseWeek(program, week);
  if (!parsed) return null;
  const days = new Set();
  let lastDay = '';
  parsed.rows.forEach((cells) => {
    const raw = String(cells[parsed.day] || '').trim();
    if (raw) lastDay = raw;
    const name = String(cells[parsed.exercise] || '').trim();
    if (!name || isWarmup(name)) return;
    const key = dayKey(lastDay);
    if (key) days.add(key);
  });
  return days;
}

// The camp schedule's own final-week row, read back as data. A rendered table
// nobody parses is a claim nobody checks.
export function campScheduleFinalWeek(program) {
  const lines = String(program || '').split('\n');
  const start = lines.findIndex((l) => /^CAMP SCHEDULE\s*$/i.test(l.trim()));
  if (start < 0) return null;
  let header = null;
  let last = null;
  for (let i = start + 1; i < lines.length && i < start + 40; i += 1) {
    const cells = lines[i].split('|').map((c) => c.trim());
    if (cells.length < 8) continue;
    if (!header && /^mon$/i.test(cells[1] || '')) { header = cells; continue; }
    if (/^W\d+$/i.test(cells[0] || '')) last = cells;
  }
  if (!header || !last) return null;
  const byDay = new Map();
  WEEKDAYS.forEach((d, i) => { byDay.set(d, String(last[i + 1] || '').trim()); });
  return { week: Number(last[0].slice(1)), byDay };
}

export function collectTimelineIntegrityFlags(program, intake = {}, now = Date.now()) {
  const week = eventWeek(intake, now);
  if (!week) return [];
  const eventDay = eventWeekday(intake);
  if (!eventDay) return [];
  const eventIndex = WEEKDAYS.indexOf(eventDay);
  const noun = eventNoun(intake).toLowerCase();
  const flags = [];

  // 1. Nothing is scheduled on the event, and nothing after it belongs here.
  const working = workingDaysOf(program, week);
  if (working) {
    const offending = [...working].filter((d) => WEEKDAYS.indexOf(d) >= eventIndex);
    if (offending.length) {
      flags.push({
        code: 'V91_SESSION_ON_OR_AFTER_DAY_ZERO',
        week,
        detail: `Week ${week} prescribes gym work on ${offending.map((d) => LABEL[d]).join(', ')}, and the event is on ${LABEL[eventDay]}. `
          + `A session cannot sit on Day 0 or beyond it: the athlete is competing, and anything after the event is not part of this block. `
          + `Move the work earlier in the week or drop it.`,
      });
    }
  }

  const schedule = campScheduleFinalWeek(program);
  if (schedule) {
    const after = WEEKDAYS
      .map((d, i) => ({ d, i, cell: schedule.byDay.get(d) || '' }))
      .filter(({ i, cell }) => i >= eventIndex && cell && cell !== '-' && !/fight day|race day|event day/i.test(cell));
    if (after.length) {
      flags.push({
        code: 'V91_CALENDAR_TRAINS_THROUGH_THE_EVENT',
        week,
        detail: `The camp schedule still prescribes ${after.map(({ d, cell }) => `${LABEL[d]} ${cell}`).join(', ')}, but the event is on ${LABEL[eventDay]}. `
          + `The calendar and the week table are two views of one week and they are saying different things about the same days. `
          + `The week containing Day 0 stops at Day 0.`,
      });
    }

    // 2. The two views must name the same working days.
    if (working) {
      const scheduleGym = new Set(
        WEEKDAYS.filter((d) => /\bgym\b/i.test(schedule.byDay.get(d) || '')),
      );
      const onlyTable = [...working].filter((d) => !scheduleGym.has(d));
      const onlySchedule = [...scheduleGym].filter((d) => !working.has(d));
      if (onlyTable.length || onlySchedule.length) {
        const parts = [];
        if (onlyTable.length) parts.push(`the week table trains on ${onlyTable.map((d) => LABEL[d]).join(', ')} and the calendar does not`);
        if (onlySchedule.length) parts.push(`the calendar shows a gym session on ${onlySchedule.map((d) => LABEL[d]).join(', ')} that the week table does not contain`);
        flags.push({
          code: 'V91_TIMELINE_VIEWS_DISAGREE',
          week,
          detail: `The calendar and the week table disagree about ${noun}: ${parts.join('; ')}. `
            + `An athlete reading the two cannot tell which is the program. They have to name the same days.`,
        });
      }
    }
  }

  // 3. Combat load has to come down into the event week -- the coach's second
  //    check, and the one a taper is actually judged by.
  const plan = sportTaperPlan(intake, now);
  if (plan && plan.length) {
    const hard = plan.map((p) => p.hardTarget);
    for (let i = 1; i < hard.length; i += 1) {
      if (hard[i] > hard[i - 1]) {
        flags.push({
          code: 'V91_COMBAT_LOAD_NOT_DECREASING',
          week: plan[i].week,
          detail: `Hard contact rises into week ${plan[i].week} (${hard.join(' -> ')}). Sparring is the largest stressor in the camp, so it has to come down as the event approaches, not up.`,
        });
        break;
      }
    }
    if (hard[hard.length - 1] > 0) {
      flags.push({
        code: 'V91_COMBAT_LOAD_NOT_DECREASING',
        week,
        detail: `The event week still carries ${hard[hard.length - 1]} hard contact session(s) (${hard.join(' -> ')}). The last damaging live exposure has to sit far enough out that soreness, cognitive fatigue and disrupted sleep have resolved before Day 0.`,
      });
    }
  }
  return flags;
}

// --- repair -----------------------------------------------------------------

// A gym session on or after the event is deleted rather than moved: the athlete
// is competing that day, and there is no other day in the block to move it to
// that is not already spoken for. Deleting a day's rows leaves the day empty,
// which is what the week should say.
export function repairTimelineIntegrity(program, intake = {}, now = Date.now()) {
  const week = eventWeek(intake, now);
  if (!week) return String(program || '');
  const eventDay = eventWeekday(intake);
  if (!eventDay) return String(program || '');
  const eventIndex = WEEKDAYS.indexOf(eventDay);

  let out = String(program || '');
  const fresh = renderCampSchedule(intake, now, { workingDays: workingDaysByWeek(out) });
  if (fresh) {
    const start = out.indexOf('CAMP SCHEDULE');
    if (start >= 0) {
      const lines = out.slice(start).split('\n');
      let end = lines.length;
      for (let i = 1; i < lines.length; i += 1) {
        if (/^START_WEEK\d+_TSV/i.test(lines[i].trim())) { end = i; break; }
      }
      const stale = lines.slice(0, end).join('\n');
      if (stale.trim() !== fresh.trim()) out = out.slice(0, start) + fresh + '\n\n' + out.slice(start + stale.length).replace(/^\s*/, '');
    }
  }

  const parsed = parseWeek(out, week);
  if (!parsed) return out;

  const keep = [];
  let lastDay = '';
  let changed = false;
  parsed.rows.forEach((cells) => {
    const raw = String(cells[parsed.day] || '').trim();
    if (raw) lastDay = raw;
    const key = dayKey(lastDay);
    if (key && WEEKDAYS.indexOf(key) >= eventIndex) { changed = true; return; }
    keep.push(cells);
  });
  if (!changed) return out;

  const rebuilt = [parsed.header.join('\t'), ...keep.map((c) => c.join('\t'))].join('\n');
  return out.replace(parsed.re, `$1${rebuilt}$3`);
}

export function buildTimelineIntegrityBrief(intake = {}, now = Date.now()) {
  const week = eventWeek(intake, now);
  const eventDay = eventWeekday(intake);
  if (!week || !eventDay) return '';
  return [
    '* THE PROGRAM MAY NOT CONTRADICT ITSELF ABOUT THE CALENDAR.',
    `  Day 0 is ${LABEL[eventDay]}. Every session in week ${week} must be named by its distance from it -- Day -4, Day -3, Day -2, Day -1 -- and the week stops there.`,
    '  NOTHING IS SCHEDULED ON DAY 0, and nothing after it belongs to this block. The athlete is competing that day.',
    '  The camp calendar and the week table are two views of one week. They must name the same training days, in the same places. If the table trains on Tuesday and Friday, the calendar shows gym on Tuesday and Friday and on no other day.',
    '  Hard contact comes down every week and reaches zero in the event week.',
  ].join('\n');
}
